<script lang="ts">
	import { ArrowUpRight, CircleAlert, Crown, Scale, X } from '@lucide/svelte';
	import Scorecard from '../Scorecard.svelte';
	import { notebookDependencies, notebookResearchFiles, scholarshipById } from '../data';
	let { selectedId, pinnedIds, leadId, coverage, warning, onSelect, onRemove, onCompare }: { selectedId:string;pinnedIds:string[];leadId:string;coverage:number;warning:string;onSelect:(id:string)=>void;onRemove:(id:string)=>void;onCompare:()=>void } = $props();
	const selectedFile = $derived(notebookResearchFiles.find((file)=>file.scholarshipId===selectedId)!);
	const blocker = $derived(notebookDependencies.find((item)=>item.scholarshipId===selectedId && (item.state==='missing'||item.type==='blocker')));
</script>

<aside class="decision-rail">
	<section><div class="rail-title"><p>Comparison tray</p><span>{pinnedIds.length} / 3</span></div><div class="pinned">{#each pinnedIds as id}{@const item=scholarshipById(id)}<div class:lead={id===leadId}><button onclick={()=>onSelect(id)}><span>{id===leadId?'Lead file':item.country}</span><strong>{item.name}</strong></button><button onclick={()=>onRemove(id)} aria-label={`Remove ${item.name} from comparison`}><X size={12}/></button></div>{/each}</div>{#if warning}<p class="warning">{warning}</p>{/if}<button class="compare" onclick={onCompare}><Scale size={14}/> Open comparison desk <ArrowUpRight size={13}/></button></section>
	<section class="readiness"><p>Selected packet readiness</p><div><strong>{coverage}%</strong><span>{scholarshipById(selectedId).name}</span></div><i><b style={`width:${coverage}%`}></b></i></section>
	<section class="action"><p><CircleAlert size={13}/> Most important blocker</p><h3>{blocker?.label ?? 'No missing dependency'}</h3><span>{blocker?.detail ?? 'This file has no critical missing requirement recorded.'}</span><strong>{blocker?.nextAction ?? selectedFile.recommendedNextAction}</strong></section>
	<section class="lead-file"><p><Crown size={13}/> Current lead contender</p><h3>{scholarshipById(leadId).name}</h3></section>
	<div class="score"><Scorecard concept="notebook" compact/></div>
</aside>

<style>
	.decision-rail{display:grid;gap:.85rem;min-width:0}.decision-rail section{border:1px solid rgba(217,191,125,.16);background:#17251f;padding:1rem;color:#eae1cf}.rail-title{display:flex;justify-content:space-between;font:700 9px "Instrument Sans Variable";letter-spacing:.14em;text-transform:uppercase;color:#bfa567}.rail-title span{font-family:"IBM Plex Mono"}.pinned{display:grid;gap:.35rem;margin-top:.8rem}.pinned>div{display:grid;grid-template-columns:1fr 30px;border-left:2px solid #617166;background:#1e3027}.pinned>div.lead{border-color:#c2a35f;background:#26382e}.pinned button{border:0;background:transparent;padding:.55rem;text-align:left;color:#eae1cf}.pinned>div>button:last-child{display:grid;place-items:center;color:#7f8d84}.pinned span,.pinned strong{display:block}.pinned span{font:700 7px "Instrument Sans Variable";text-transform:uppercase;letter-spacing:.1em;color:#a89262}.pinned strong{margin-top:.2rem;font:600 10px/1.25 "Instrument Sans Variable"}.warning{margin-top:.7rem;border-left:2px solid #9b5c4b;padding-left:.55rem;font:500 9px/1.4 "Instrument Sans Variable";color:#d0a293}.compare{display:flex;width:100%;align-items:center;justify-content:space-between;gap:.4rem;margin-top:.8rem;border:1px solid #c0a461;background:#c0a461;padding:.7rem;font:700 8px "Instrument Sans Variable";text-transform:uppercase;letter-spacing:.1em;color:#17251f}.readiness p,.action p,.lead-file p{display:flex;align-items:center;gap:.4rem;font:700 8px "Instrument Sans Variable";text-transform:uppercase;letter-spacing:.11em;color:#a89262}.readiness>div{display:flex;align-items:end;justify-content:space-between;gap:.6rem;margin-top:.7rem}.readiness strong{font:600 32px/1 "IBM Plex Mono";color:#d9c68f}.readiness span{max-width:130px;text-align:right;font:600 9px/1.3 "Instrument Sans Variable";color:#89968d}.readiness i{display:block;height:2px;margin-top:.8rem;background:#2d4036}.readiness b{display:block;height:100%;background:#b8a163}.action h3,.lead-file h3{margin-top:.65rem;font:500 23px/1 "Newsreader Variable"}.action span,.action strong{display:block;margin-top:.55rem;font:500 10px/1.5 "Instrument Sans Variable";color:#8e9a92}.action strong{border-top:1px solid rgba(217,191,125,.12);padding-top:.55rem;color:#c4ad74}.score{color:#eae1cf}@media(min-width:1024px){.decision-rail{position:sticky;top:1rem;align-self:start}}
</style>
